# Generated by Django 2.0 on 2019-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190508_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('television', 'Television'), ('refrigerator', 'Refrigerator')], default='None', max_length=30, null=True),
        ),
    ]
