# Generated by Django 2.0 on 2019-05-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_prize', models.CharField(max_length=150)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
            ],
        ),
    ]
